[package]
name = "aoc2017"
version = "0.1.0"
authors = ["Gr√©gory OBANOS <gregory.obanos@gmail.com>"]

[dependencies]
# WORKSPACE DEPS
day7_parser = { path = "day7_parser" }

# EXTERNAL DEPS
petgraph = "*"

[workspace]